services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-backend
#    dns:
#      - 8.8.8.8
#      - 8.8.4.4
    ports:
      - "8000:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
    environment:
      APP_ENV: production
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root123456
      MYSQL_DB: go_alpha
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OPENWEATHER_KEY: ${OPENWEATHER_KEY}
      WEATHERAPI_KEY: ${WEATHERAPI_KEY}
    restart: always
    volumes:
      - ./assets/avatar:/app/assets/avatar

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: go_alpha
    volumes:
      - mysql_data:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot123456"]
#      interval: 5s
#      timeout: 5s
#      retries: 20
#      start_period: 20s

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 3s
#      retries: 20
#      start_period: 5s

volumes:
  mysql_data:
  redis_data:
